/** [GGL] Auto-generated by npm run robots:sync-worker — do not edit by hand. */

/** @type {Record<string, string>} */
export const ROBOTS_BY_HOST = {
  'alumineu.pl': `# Merchant Center / Google Shopping — явный доступ краулерам Google
User-agent: Googlebot
Allow: /

User-agent: Googlebot-Image
Allow: /

User-agent: AdsBot-Google
Allow: /

User-agent: *
Allow: /
# Общие запреты для всех поисковиков (включая Google)
Disallow: /tilda/
Disallow: /page43514570.html
Disallow: /page43514572.html
Disallow: /page43514573.html
Disallow: /error
Disallow: /page64034209.html
Disallow: /page60293665.html
Disallow: /page63887195.html
Disallow: /produkty/profile-harpunowe/bezszczelinowe/classix-x111
Disallow: /page63887585.html
Disallow: /produkty/profile-harpunowe/bezszczelinowe/classix-x112
Disallow: /page63886635.html
Disallow: /produkty/profile-harpunowe/bezszczelinowe/classix-x110
Disallow: /page44200321.html
Disallow: /dostawa
Disallow: /page88580906.html
Disallow: /polityka-prywatnosci
Disallow: /page92082366.html
Disallow: /wysylka-i-zwrot
Disallow: /page68291507.html
Disallow: /page43992133.html
Disallow: /page60246019.html
Disallow: /page60669633.html
Disallow: /page59762987.html
Disallow: /page60878615.html
Disallow: /page60818585.html
Disallow: /page60879327.html
Disallow: /page60889247.html
Disallow: /page61352579.html
Disallow: /page61405567.html
Disallow: /page62780333.html
Disallow: /page61405359.html
Disallow: /page66576263.html
Disallow: /page70534211.html
Disallow: /produkty/oswietlenie/tasmy-led
Disallow: /page70534377.html
Disallow: /produkty/oswietlenie/zasilacze
Disallow: /page70583771.html
Disallow: /produkty/oswietlenie/lampy-punktowe
Disallow: /page70584059.html
Disallow: /produkty/oswietlenie/lampy-punktowe/natynkowe
Disallow: /page70584363.html
Disallow: /produkty/oswietlenie/lampy-punktowe/wpuszczane
Disallow: /tilda/form*
Disallow: /tilda/rec*
Disallow: /tilda/click*
Disallow: /tilda/scroll*
Disallow: /tilda/popup*
Disallow: /tilda/cart*
Disallow: /tilda/product*
Disallow: /tilda/event*
Disallow: /members/login*
Disallow: /members/signup*

# Явное открытие картинок и товарных объявлений для Google Merchant / Google Shopping
User-agent: AdsBot-Google
Allow: /produkty/
Allow: /tilda/images/

Sitemap: https://alumineu.pl/sitemap.xml
Sitemap: https://alumineu.pl/sitemap-store.xml
Sitemap: https://alumineu.pl/sitemap-feeds.xml`,
  'www.alumineu.pl': `# Merchant Center / Google Shopping — явный доступ краулерам Google
User-agent: Googlebot
Allow: /

User-agent: Googlebot-Image
Allow: /

User-agent: AdsBot-Google
Allow: /

User-agent: *
Allow: /
# Общие запреты для всех поисковиков (включая Google)
Disallow: /tilda/
Disallow: /page43514570.html
Disallow: /page43514572.html
Disallow: /page43514573.html
Disallow: /error
Disallow: /page64034209.html
Disallow: /page60293665.html
Disallow: /page63887195.html
Disallow: /produkty/profile-harpunowe/bezszczelinowe/classix-x111
Disallow: /page63887585.html
Disallow: /produkty/profile-harpunowe/bezszczelinowe/classix-x112
Disallow: /page63886635.html
Disallow: /produkty/profile-harpunowe/bezszczelinowe/classix-x110
Disallow: /page44200321.html
Disallow: /dostawa
Disallow: /page88580906.html
Disallow: /polityka-prywatnosci
Disallow: /page92082366.html
Disallow: /wysylka-i-zwrot
Disallow: /page68291507.html
Disallow: /page43992133.html
Disallow: /page60246019.html
Disallow: /page60669633.html
Disallow: /page59762987.html
Disallow: /page60878615.html
Disallow: /page60818585.html
Disallow: /page60879327.html
Disallow: /page60889247.html
Disallow: /page61352579.html
Disallow: /page61405567.html
Disallow: /page62780333.html
Disallow: /page61405359.html
Disallow: /page66576263.html
Disallow: /page70534211.html
Disallow: /produkty/oswietlenie/tasmy-led
Disallow: /page70534377.html
Disallow: /produkty/oswietlenie/zasilacze
Disallow: /page70583771.html
Disallow: /produkty/oswietlenie/lampy-punktowe
Disallow: /page70584059.html
Disallow: /produkty/oswietlenie/lampy-punktowe/natynkowe
Disallow: /page70584363.html
Disallow: /produkty/oswietlenie/lampy-punktowe/wpuszczane
Disallow: /tilda/form*
Disallow: /tilda/rec*
Disallow: /tilda/click*
Disallow: /tilda/scroll*
Disallow: /tilda/popup*
Disallow: /tilda/cart*
Disallow: /tilda/product*
Disallow: /tilda/event*
Disallow: /members/login*
Disallow: /members/signup*

# Явное открытие картинок и товарных объявлений для Google Merchant / Google Shopping
User-agent: AdsBot-Google
Allow: /produkty/
Allow: /tilda/images/

Sitemap: https://alumineu.pl/sitemap.xml
Sitemap: https://alumineu.pl/sitemap-store.xml
Sitemap: https://alumineu.pl/sitemap-feeds.xml`,
  'alumineu.de': `# Merchant Center / Google Shopping — явный доступ краулерам Google
User-agent: Googlebot
Allow: /

User-agent: Googlebot-Image
Allow: /

User-agent: AdsBot-Google
Allow: /

User-agent: AdsBot-Google
Allow: /

User-Agent: *
Disallow: /page67132641.html
Disallow: /page67136879.html
Disallow: /page67663357.html
Disallow: /produkte/zubehor/vorhanghaken
Disallow: /page67663435.html
Disallow: /produkte/zubehor/vorhanghaken/hookara-y701
Disallow: /page100365596.html
Disallow: /produkte/zubehor/vorhanghaken/slidene-y702
Disallow: /page100227196.html
Disallow: /produkte/zubehor/vorhanghaken/slidene-y703
Disallow: /page67663441.html
Disallow: /produkte/zubehor/vorhanghaken/hookend-y704
Disallow: /page68046037.html
Disallow: /page90885536.html
Disallow: /datenschutzerklarung
Disallow: /page90886736.html
Disallow: /versand-und-ruckgabe
Disallow: /page67699947.html
Disallow: /page67708963.html
Disallow: /page91909456.html
Disallow: /produkte/beleuchtung/led-streifen
Disallow: /page91909466.html
Disallow: /page91909486.html
Disallow: /page91909496.html
Disallow: /page91909506.html
Disallow: /tilda/form*
Disallow: /tilda/rec*
Disallow: /tilda/click*
Disallow: /tilda/scroll*
Disallow: /tilda/popup*
Disallow: /tilda/cart*
Disallow: /tilda/product*
Disallow: /tilda/event*
Disallow: /members/login*
Disallow: /members/signup*
Disallow:

Sitemap: https://alumineu.de/sitemap.xml
Sitemap: https://alumineu.de/sitemap-store.xml`,
  'www.alumineu.de': `# Merchant Center / Google Shopping — явный доступ краулерам Google
User-agent: Googlebot
Allow: /

User-agent: Googlebot-Image
Allow: /

User-agent: AdsBot-Google
Allow: /

User-agent: AdsBot-Google
Allow: /

User-Agent: *
Disallow: /page67132641.html
Disallow: /page67136879.html
Disallow: /page67663357.html
Disallow: /produkte/zubehor/vorhanghaken
Disallow: /page67663435.html
Disallow: /produkte/zubehor/vorhanghaken/hookara-y701
Disallow: /page100365596.html
Disallow: /produkte/zubehor/vorhanghaken/slidene-y702
Disallow: /page100227196.html
Disallow: /produkte/zubehor/vorhanghaken/slidene-y703
Disallow: /page67663441.html
Disallow: /produkte/zubehor/vorhanghaken/hookend-y704
Disallow: /page68046037.html
Disallow: /page90885536.html
Disallow: /datenschutzerklarung
Disallow: /page90886736.html
Disallow: /versand-und-ruckgabe
Disallow: /page67699947.html
Disallow: /page67708963.html
Disallow: /page91909456.html
Disallow: /produkte/beleuchtung/led-streifen
Disallow: /page91909466.html
Disallow: /page91909486.html
Disallow: /page91909496.html
Disallow: /page91909506.html
Disallow: /tilda/form*
Disallow: /tilda/rec*
Disallow: /tilda/click*
Disallow: /tilda/scroll*
Disallow: /tilda/popup*
Disallow: /tilda/cart*
Disallow: /tilda/product*
Disallow: /tilda/event*
Disallow: /members/login*
Disallow: /members/signup*
Disallow:

Sitemap: https://alumineu.de/sitemap.xml
Sitemap: https://alumineu.de/sitemap-store.xml`,
  'alumineu.ro': `# Merchant Center / Google Shopping — явный доступ краулерам Google
User-agent: Googlebot
Allow: /

User-agent: Googlebot-Image
Allow: /

User-agent: AdsBot-Google
Allow: /

User-agent: AdsBot-Google
Allow: /

# Snapshot 2026-06 — alumineu.ro (Tilda tail after Cloudflare managed block stripped on build)
User-Agent: *
Disallow: /page72695897.html
Disallow: /produse/iluminat
Disallow: /page73812719.html
Disallow: /page73813015.html
Disallow: /page82755536.html
Disallow: /produse/iluminat/sisteme-cu-in
Disallow: /page82755546.html
Disallow: /produse/iluminat/band-led
Disallow: /page82755556.html
Disallow: /produse/iluminat/spoturi/surse-de-alimentare
Disallow: /page82755566.html
Disallow: /produse/iluminat/spoturi
Disallow: /page82755576.html
Disallow: /produse/iluminat/spoturi-aplicate
Disallow: /page82755586.html
Disallow: /page84766036.html
Disallow: /page88493636.html
Disallow: /page92084986.html
Disallow: /politica-de-confidentialitate
Disallow: /page92084996.html
Disallow: /expediere-si-returnare
Disallow: /tilda/form*
Disallow: /tilda/rec*
Disallow: /tilda/click*
Disallow: /tilda/scroll*
Disallow: /tilda/popup*
Disallow: /tilda/cart*
Disallow: /tilda/product*
Disallow: /tilda/event*
Disallow:

Sitemap: https://alumineu.ro/sitemap.xml
Sitemap: https://alumineu.ro/sitemap-store.xml`,
  'www.alumineu.ro': `# Merchant Center / Google Shopping — явный доступ краулерам Google
User-agent: Googlebot
Allow: /

User-agent: Googlebot-Image
Allow: /

User-agent: AdsBot-Google
Allow: /

User-agent: AdsBot-Google
Allow: /

# Snapshot 2026-06 — alumineu.ro (Tilda tail after Cloudflare managed block stripped on build)
User-Agent: *
Disallow: /page72695897.html
Disallow: /produse/iluminat
Disallow: /page73812719.html
Disallow: /page73813015.html
Disallow: /page82755536.html
Disallow: /produse/iluminat/sisteme-cu-in
Disallow: /page82755546.html
Disallow: /produse/iluminat/band-led
Disallow: /page82755556.html
Disallow: /produse/iluminat/spoturi/surse-de-alimentare
Disallow: /page82755566.html
Disallow: /produse/iluminat/spoturi
Disallow: /page82755576.html
Disallow: /produse/iluminat/spoturi-aplicate
Disallow: /page82755586.html
Disallow: /page84766036.html
Disallow: /page88493636.html
Disallow: /page92084986.html
Disallow: /politica-de-confidentialitate
Disallow: /page92084996.html
Disallow: /expediere-si-returnare
Disallow: /tilda/form*
Disallow: /tilda/rec*
Disallow: /tilda/click*
Disallow: /tilda/scroll*
Disallow: /tilda/popup*
Disallow: /tilda/cart*
Disallow: /tilda/product*
Disallow: /tilda/event*
Disallow:

Sitemap: https://alumineu.ro/sitemap.xml
Sitemap: https://alumineu.ro/sitemap-store.xml`,
  'alumineu.com': `# Merchant Center / Google Shopping — явный доступ краулерам Google
User-agent: Googlebot
Allow: /

User-agent: Googlebot-Image
Allow: /

User-agent: AdsBot-Google
Allow: /

# Placeholder — обновите: npm run robots:download (когда alumineu.com резолвится)
User-Agent: *
Disallow: /tilda/form*
Disallow: /tilda/rec*
Disallow: /tilda/click*
Disallow: /tilda/scroll*
Disallow: /tilda/popup*
Disallow: /tilda/cart*
Disallow: /tilda/product*
Disallow: /tilda/event*
Disallow: /members/login*
Disallow: /members/signup*
Disallow:

Sitemap: https://alumineu.com/sitemap.xml
Sitemap: https://alumineu.com/sitemap-store.xml`,
  'www.alumineu.com': `# Merchant Center / Google Shopping — явный доступ краулерам Google
User-agent: Googlebot
Allow: /

User-agent: Googlebot-Image
Allow: /

User-agent: AdsBot-Google
Allow: /

# Placeholder — обновите: npm run robots:download (когда alumineu.com резолвится)
User-Agent: *
Disallow: /tilda/form*
Disallow: /tilda/rec*
Disallow: /tilda/click*
Disallow: /tilda/scroll*
Disallow: /tilda/popup*
Disallow: /tilda/cart*
Disallow: /tilda/product*
Disallow: /tilda/event*
Disallow: /members/login*
Disallow: /members/signup*
Disallow:

Sitemap: https://alumineu.com/sitemap.xml
Sitemap: https://alumineu.com/sitemap-store.xml`,
};
